"""create warehouses

Revision ID: 01b1105a9213
Revises: a76da06d23e1
Create Date: 2025-10-19 15:50:43.980974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b1105a9213'
down_revision: Union[str, Sequence[str], None] = 'a76da06d23e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('adress', sa.String(length=255), nullable=False),
    sa.Column('row_x', sa.Integer(), nullable=False),
    sa.Column('row_y', sa.Integer(), nullable=False),
    sa.Column('products_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouses')
    # ### end Alembic commands ###
