"""fix FKs/types

Revision ID: 07587bd50dd0
Revises: a753f9584e74
Create Date: 2025-10-31 16:43:07.365661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07587bd50dd0'
down_revision: Union[str, Sequence[str], None] = 'a753f9584e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'shipped', 'canceled', 'rescheduled', name='shipment_status', native_enum=False), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_name'), 'shipments', ['name'], unique=False)
    op.create_index(op.f('ix_shipments_scheduled_at'), 'shipments', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_shipments_shipped_at'), 'shipments', ['shipped_at'], unique=False)
    op.create_table('shipment_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('fact_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_product_id'), 'shipment_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_warehouse_id'), 'shipment_items', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_items_warehouse_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_product_id'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index(op.f('ix_shipments_shipped_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_scheduled_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_name'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
