"""address in warehouse

Revision ID: 13a9b63b0828
Revises: ab63daccc232
Create Date: 2025-10-21 16:50:18.942756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a9b63b0828'
down_revision: Union[str, Sequence[str], None] = 'ab63daccc232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('address', sa.String(length=255), nullable=False))
    op.drop_column('warehouses', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('adress', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('warehouses', 'address')
    # ### end Alembic commands ###
