"""init

Revision ID: 206790de3441
Revises: 
Create Date: 2025-10-18 15:52:29.665977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206790de3441'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_zone', sa.String(), nullable=False),
    sa.Column('current_row', sa.Integer(), nullable=False),
    sa.Column('current_shelf', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robots')
    # ### end Alembic commands ###
