"""add predict_at ta

Revision ID: 252067ee0c38
Revises: 85770d1a5e30
Create Date: 2025-10-31 20:02:33.062386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252067ee0c38'
down_revision: Union[str, Sequence[str], None] = '85770d1a5e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict_at',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('depletion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predict_at_product_id'), 'predict_at', ['product_id'], unique=False)
    op.create_index(op.f('ix_predict_at_warehouse_id'), 'predict_at', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predict_at_warehouse_id'), table_name='predict_at')
    op.drop_index(op.f('ix_predict_at_product_id'), table_name='predict_at')
    op.drop_table('predict_at')
    # ### end Alembic commands ###
