"""edit warehouse

Revision ID: 37e2309e6dd4
Revises: 6b6a93f99628
Create Date: 2025-10-21 17:51:46.201579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e2309e6dd4'
down_revision: Union[str, Sequence[str], None] = '6b6a93f99628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('max_products', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'max_products')
    # ### end Alembic commands ###
