"""add last_scanned_at to prods
Revision ID: 46624abbe099
Revises: 144a26a8c705
Create Date: 2025-10-28 22:16:32.585887
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46624abbe099'
down_revision: Union[str, Sequence[str], None] = '144a26a8c705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_products_last_scanned_at'), 'products', ['last_scanned_at'], unique=False)
    op.create_index('ix_products_wh_cell_lastscan', 'products', ['warehouse_id', 'current_row', 'current_shelf', 'last_scanned_at'], unique=False, postgresql_include=('id', 'name', 'category', 'article', 'stock', 'min_stock', 'optimal_stock'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_wh_cell_lastscan', table_name='products', postgresql_include=('id', 'name', 'category', 'article', 'stock', 'min_stock', 'optimal_stock'))
    op.drop_index(op.f('ix_products_last_scanned_at'), table_name='products')
    op.drop_column('products', 'last_scanned_at')
    # ### end Alembic commands ###