"""create predict_at table

Revision ID: 5e826abc7fd2
Revises: 62f8f50ede0a
Create Date: 2025-10-31 22:52:03.351515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e826abc7fd2'
down_revision: Union[str, Sequence[str], None] = '62f8f50ede0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict_at', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('predict_at', sa.Column('depletion_at_p10', sa.DateTime(timezone=True), nullable=True))
    op.add_column('predict_at', sa.Column('depletion_at_p90', sa.DateTime(timezone=True), nullable=True))
    op.add_column('predict_at', sa.Column('p_deplete_within', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predict_at', 'p_deplete_within')
    op.drop_column('predict_at', 'depletion_at_p90')
    op.drop_column('predict_at', 'depletion_at_p10')
    op.drop_column('predict_at', 'product_name')
    # ### end Alembic commands ###
