"""Убрал автоудаление записей

Revision ID: 6500004d4fdc
Revises: fc834c90976f
Create Date: 2025-10-27 01:42:34.083955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6500004d4fdc'
down_revision: Union[str, Sequence[str], None] = 'fc834c90976f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventory_history_product_id_fkey'), 'inventory_history', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_history', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.alter_column('robot_history', 'robot_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('robot_history_robot_id_fkey'), 'robot_history', type_='foreignkey')
    op.create_foreign_key(None, 'robot_history', 'robots', ['robot_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'robot_history', type_='foreignkey')
    op.create_foreign_key(op.f('robot_history_robot_id_fkey'), 'robot_history', 'robots', ['robot_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('robot_history', 'robot_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'inventory_history', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_history_product_id_fkey'), 'inventory_history', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
