"""Добавление табилицы RobotHistory

Revision ID: 919c77b4b983
Revises: 9fe85ae44113
Create Date: 2025-10-25 11:19:09.176055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919c77b4b983'
down_revision: Union[str, Sequence[str], None] = '9fe85ae44113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot_history',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('robot_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rh_robot_created', 'robot_history', ['robot_id', 'created_at'], unique=False)
    op.create_index('ix_rh_wh_created', 'robot_history', ['warehouse_id', 'created_at'], unique=False)
    op.create_index('ix_rh_wh_status_created', 'robot_history', ['warehouse_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_robot_history_created_at'), 'robot_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_robot_history_robot_id'), 'robot_history', ['robot_id'], unique=False)
    op.create_index(op.f('ix_robot_history_warehouse_id'), 'robot_history', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_history_warehouse_id'), table_name='robot_history')
    op.drop_index(op.f('ix_robot_history_robot_id'), table_name='robot_history')
    op.drop_index(op.f('ix_robot_history_created_at'), table_name='robot_history')
    op.drop_index('ix_rh_wh_status_created', table_name='robot_history')
    op.drop_index('ix_rh_wh_created', table_name='robot_history')
    op.drop_index('ix_rh_robot_created', table_name='robot_history')
    op.drop_table('robot_history')
    # ### end Alembic commands ###
