"""relations warehouse and robot

Revision ID: 9cdfb9fc94ed
Revises: 68cb640b0c7e
Create Date: 2025-10-19 18:23:41.732288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdfb9fc94ed'
down_revision: Union[str, Sequence[str], None] = '68cb640b0c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('warehouse_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_robots_warehouse_id'), 'robots', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'robots', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'robots', type_='foreignkey')
    op.drop_index(op.f('ix_robots_warehouse_id'), table_name='robots')
    op.drop_column('robots', 'warehouse_id')
    # ### end Alembic commands ###
