"""edit shelf to str

Revision ID: a3b0e6cdb5f9
Revises: a725b47e1f0d
Create Date: 2025-10-22 15:49:40.625708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b0e6cdb5f9'
down_revision: Union[str, Sequence[str], None] = 'a725b47e1f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_history', sa.Column('article', sa.String(length=100), nullable=False))
    op.alter_column('inventory_history', 'current_zone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory_history', 'current_shelf',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('products', sa.Column('article', sa.String(length=100), nullable=False))
    op.alter_column('products', 'current_shelf',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'current_shelf',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('products', 'article')
    op.alter_column('inventory_history', 'current_shelf',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('inventory_history', 'current_zone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('inventory_history', 'article')
    # ### end Alembic commands ###
