"""edit InventoryHistory

Revision ID: a725b47e1f0d
Revises: 37e2309e6dd4
Create Date: 2025-10-21 19:04:30.797990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a725b47e1f0d'
down_revision: Union[str, Sequence[str], None] = '37e2309e6dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_history', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('inventory_history', sa.Column('status', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_inventory_history_prod_created'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_robot_created'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_wh_created'), table_name='inventory_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_history_wh_created'), 'inventory_history', ['warehouse_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_history_robot_created'), 'inventory_history', ['robot_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_history_prod_created'), 'inventory_history', ['product_id', 'created_at'], unique=False)
    op.drop_column('inventory_history', 'status')
    op.drop_column('inventory_history', 'stock')
    # ### end Alembic commands ###
