"""add inventory_history with FKs to warehouse/product/robot

Revision ID: a8c503d754ef
Revises: e36eb620674b
Create Date: 2025-10-20 19:06:13.442657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c503d754ef'
down_revision: Union[str, Sequence[str], None] = 'e36eb620674b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
