"""add inventory_history with FKs to warehouse/product/robt

Revision ID: ab63daccc232
Revises: a8c503d754ef
Create Date: 2025-10-20 19:08:49.966701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab63daccc232'
down_revision: Union[str, Sequence[str], None] = 'a8c503d754ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_history',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('robot_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('current_zone', sa.String(), nullable=True),
    sa.Column('current_row', sa.Integer(), nullable=False),
    sa.Column('current_shelf', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('optimal_stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_history_created_at'), 'inventory_history', ['created_at'], unique=False)
    op.create_index('ix_inventory_history_prod_created', 'inventory_history', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_history_product_id'), 'inventory_history', ['product_id'], unique=False)
    op.create_index('ix_inventory_history_robot_created', 'inventory_history', ['robot_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_history_robot_id'), 'inventory_history', ['robot_id'], unique=False)
    op.create_index(op.f('ix_inventory_history_warehouse_id'), 'inventory_history', ['warehouse_id'], unique=False)
    op.create_index('ix_inventory_history_wh_created', 'inventory_history', ['warehouse_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_history_wh_created', table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_warehouse_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_robot_id'), table_name='inventory_history')
    op.drop_index('ix_inventory_history_robot_created', table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_product_id'), table_name='inventory_history')
    op.drop_index('ix_inventory_history_prod_created', table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_created_at'), table_name='inventory_history')
    op.drop_table('inventory_history')
    # ### end Alembic commands ###
