"""Initial

Revision ID: be10170239e2
Revises: 
Create Date: 2025-10-31 19:40:21.541305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be10170239e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_history_warehouse_id'), table_name='inventory_history')
    op.drop_constraint(op.f('inventory_history_warehouse_id_fkey'), 'inventory_history', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_history', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_products_warehouse_id'), table_name='products')
    op.create_index(op.f('ix_products_last_scanned_at'), 'products', ['last_scanned_at'], unique=False)
    op.create_index('ix_products_wh_cell_lastscan', 'products', ['warehouse_id', 'current_row', 'current_shelf', 'last_scanned_at'], unique=False, postgresql_include=('id', 'name', 'category', 'article', 'stock', 'min_stock', 'optimal_stock'))
    op.drop_constraint(op.f('products_warehouse_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_robot_history_warehouse_id'), table_name='robot_history')
    op.drop_constraint(op.f('robot_history_warehouse_id_fkey'), 'robot_history', type_='foreignkey')
    op.create_foreign_key(None, 'robot_history', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_robots_warehouse_id'), table_name='robots')
    op.drop_constraint(op.f('robots_warehouse_id_fkey'), 'robots', type_='foreignkey')
    op.create_foreign_key(None, 'robots', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shipments_warehouse_id'), table_name='shipments')
    op.drop_constraint(op.f('shipments_warehouse_id_fkey'), 'shipments', type_='foreignkey')
    op.create_foreign_key(None, 'shipments', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.create_foreign_key(op.f('shipments_warehouse_id_fkey'), 'shipments', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_index(op.f('ix_shipments_warehouse_id'), 'shipments', ['warehouse_id'], unique=False)
    op.drop_constraint(None, 'robots', type_='foreignkey')
    op.create_foreign_key(op.f('robots_warehouse_id_fkey'), 'robots', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('ix_robots_warehouse_id'), 'robots', ['warehouse_id'], unique=False)
    op.drop_constraint(None, 'robot_history', type_='foreignkey')
    op.create_foreign_key(op.f('robot_history_warehouse_id_fkey'), 'robot_history', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('ix_robot_history_warehouse_id'), 'robot_history', ['warehouse_id'], unique=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_warehouse_id_fkey'), 'products', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index('ix_products_wh_cell_lastscan', table_name='products', postgresql_include=('id', 'name', 'category', 'article', 'stock', 'min_stock', 'optimal_stock'))
    op.drop_index(op.f('ix_products_last_scanned_at'), table_name='products')
    op.create_index(op.f('ix_products_warehouse_id'), 'products', ['warehouse_id'], unique=False)
    op.drop_column('products', 'last_scanned_at')
    op.drop_constraint(None, 'inventory_history', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_history_warehouse_id_fkey'), 'inventory_history', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('ix_inventory_history_warehouse_id'), 'inventory_history', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###
