"""Add new models

Revision ID: c73e85db302e
Revises: d0cd90214af1
Create Date: 2025-10-31 18:16:56.477705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73e85db302e'
down_revision: Union[str, Sequence[str], None] = 'd0cd90214af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'arrived', 'canceled', 'rescheduled', name='delivery_status', native_enum=False), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_delivered_at'), 'deliveries', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_deliveries_name'), 'deliveries', ['name'], unique=False)
    op.create_index(op.f('ix_deliveries_scheduled_at'), 'deliveries', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_deliveries_warehouse_id'), 'deliveries', ['warehouse_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'shipped', 'canceled', 'rescheduled', name='shipment_status', native_enum=False), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_name'), 'shipments', ['name'], unique=False)
    op.create_index(op.f('ix_shipments_scheduled_at'), 'shipments', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_shipments_shipped_at'), 'shipments', ['shipped_at'], unique=False)
    op.create_index(op.f('ix_shipments_warehouse_id'), 'shipments', ['warehouse_id'], unique=False)
    op.create_table('delivery_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('delivery_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('fact_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_items_delivery_id'), 'delivery_items', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_items_product_id'), 'delivery_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_delivery_items_warehouse_id'), 'delivery_items', ['warehouse_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('fact_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_product_id'), 'shipment_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_warehouse_id'), 'shipment_items', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_items_warehouse_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_product_id'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index(op.f('ix_delivery_items_warehouse_id'), table_name='delivery_items')
    op.drop_index(op.f('ix_delivery_items_product_id'), table_name='delivery_items')
    op.drop_index(op.f('ix_delivery_items_delivery_id'), table_name='delivery_items')
    op.drop_table('delivery_items')
    op.drop_index(op.f('ix_shipments_warehouse_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipped_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_scheduled_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_name'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_deliveries_warehouse_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_scheduled_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_name'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivered_at'), table_name='deliveries')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
