"""add relations warehouse and product

Revision ID: d00ba957027f
Revises: 01b1105a9213
Create Date: 2025-10-19 17:14:18.801870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00ba957027f'
down_revision: Union[str, Sequence[str], None] = '01b1105a9213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('warehouse_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_products_warehouse_id'), 'products', ['warehouse_id'], unique=False)
    op.create_index('ix_products_warehouse_id_name', 'products', ['warehouse_id', 'name'], unique=False)
    op.create_foreign_key(None, 'products', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index('ix_products_warehouse_id_name', table_name='products')
    op.drop_index(op.f('ix_products_warehouse_id'), table_name='products')
    op.drop_column('products', 'warehouse_id')
    # ### end Alembic commands ###
