"""Добавление индексов для оптимизации

Revision ID: d0cd90214af1
Revises: 6500004d4fdc
Create Date: 2025-10-27 16:59:55.106813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cd90214af1'
down_revision: Union[str, Sequence[str], None] = '6500004d4fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_history', 'current_zone',
               existing_type=sa.VARCHAR(),
               server_default='Хранение',
               existing_nullable=False)
    op.alter_column('inventory_history', 'current_row',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('inventory_history', 'current_shelf',
               existing_type=sa.VARCHAR(),
               server_default='A',
               existing_nullable=False)
    op.alter_column('inventory_history', 'article',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index('ix_inv_hist_robot_created', 'inventory_history', ['robot_id', 'created_at'], unique=False)
    op.create_index('ix_inv_hist_wh_created', 'inventory_history', ['warehouse_id', 'created_at'], unique=False)
    op.create_index('ix_inv_hist_wh_prod_created', 'inventory_history', ['warehouse_id', 'product_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('inventory_history_product_id_fkey'), 'inventory_history', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_history', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'article',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               server_default='100',
               existing_nullable=False)
    op.alter_column('products', 'min_stock',
               existing_type=sa.INTEGER(),
               server_default='20',
               existing_nullable=False)
    op.alter_column('products', 'optimal_stock',
               existing_type=sa.INTEGER(),
               server_default='80',
               existing_nullable=False)
    op.alter_column('products', 'current_zone',
               existing_type=sa.VARCHAR(),
               server_default='Хранение',
               existing_nullable=False)
    op.alter_column('products', 'current_row',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('products', 'current_shelf',
               existing_type=sa.VARCHAR(),
               server_default='A',
               existing_nullable=False)
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(),
               server_default='ok',
               existing_nullable=False)
    op.drop_index(op.f('ix_products_warehouse_id_name'), table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index('ix_products_wh_name', 'products', ['warehouse_id', 'name'], unique=False)
    op.create_index('ix_products_wh_row_shelf', 'products', ['warehouse_id', 'current_row', 'current_shelf'], unique=False)
    op.alter_column('robots', 'status',
               existing_type=sa.VARCHAR(),
               server_default='idle',
               existing_nullable=False)
    op.alter_column('robots', 'battery_level',
               existing_type=sa.INTEGER(),
               server_default='100',
               existing_nullable=False)
    op.alter_column('robots', 'current_zone',
               existing_type=sa.VARCHAR(),
               server_default='Хранение',
               existing_nullable=False)
    op.alter_column('robots', 'current_row',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('robots', 'current_shelf',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.create_index('ix_robots_wh_status', 'robots', ['warehouse_id', 'status'], unique=False)
    op.add_column('warehouses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('warehouses', 'max_products',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('warehouses', 'row_x',
               existing_type=sa.INTEGER(),
               server_default='26',
               existing_nullable=False)
    op.alter_column('warehouses', 'row_y',
               existing_type=sa.INTEGER(),
               server_default='50',
               existing_nullable=False)
    op.alter_column('warehouses', 'products_count',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouses', 'products_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('warehouses', 'row_y',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('warehouses', 'row_x',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('warehouses', 'max_products',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('warehouses', 'created_at')
    op.drop_index('ix_robots_wh_status', table_name='robots')
    op.alter_column('robots', 'current_shelf',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('robots', 'current_row',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('robots', 'current_zone',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('robots', 'battery_level',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('robots', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_products_wh_row_shelf', table_name='products')
    op.drop_index('ix_products_wh_name', table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_warehouse_id_name'), 'products', ['warehouse_id', 'name'], unique=False)
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'current_shelf',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'current_row',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'current_zone',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'optimal_stock',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'min_stock',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'article',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'inventory_history', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_history_product_id_fkey'), 'inventory_history', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_inv_hist_wh_prod_created', table_name='inventory_history')
    op.drop_index('ix_inv_hist_wh_created', table_name='inventory_history')
    op.drop_index('ix_inv_hist_robot_created', table_name='inventory_history')
    op.alter_column('inventory_history', 'article',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('inventory_history', 'current_shelf',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inventory_history', 'current_row',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inventory_history', 'current_zone',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
