"""init schema

Revision ID: da4573cb9f66
Revises: 
Create Date: 2025-10-31 21:12:39.369765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4573cb9f66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('message2', sa.String(), nullable=True))
    op.add_column('alarms', sa.Column('message3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarms', 'message3')
    op.drop_column('alarms', 'message2')
    # ### end Alembic commands ###
