"""Add warehouse_id to shipments and FK to warehouses

Revision ID: daa70bc7b0cc
Revises: 09d1a59091ab
Create Date: 2025-10-31 16:22:53.154148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa70bc7b0cc'
down_revision: Union[str, Sequence[str], None] = '09d1a59091ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
