"""upgrade

Revision ID: e36eb620674b
Revises: 9cdfb9fc94ed
Create Date: 2025-10-20 18:22:05.858221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36eb620674b'
down_revision: Union[str, Sequence[str], None] = '9cdfb9fc94ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('current_zone', sa.String(), nullable=False))
    op.add_column('products', sa.Column('current_row', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('current_shelf', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'current_shelf')
    op.drop_column('products', 'current_row')
    op.drop_column('products', 'current_zone')
    # ### end Alembic commands ###
