"""Delivery

Revision ID: e59f76ac4e7d
Revises: 9c2becefa223
Create Date: 2025-10-31 18:07:23.886101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59f76ac4e7d'
down_revision: Union[str, Sequence[str], None] = '9c2becefa223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'arrived', 'canceled', 'rescheduled', name='delivery_status', native_enum=False), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_delivered_at'), 'deliveries', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_deliveries_name'), 'deliveries', ['name'], unique=False)
    op.create_index(op.f('ix_deliveries_scheduled_at'), 'deliveries', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_deliveries_warehouse_id'), 'deliveries', ['warehouse_id'], unique=False)
    op.create_table('delivery_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('delivery_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('fact_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_items_delivery_id'), 'delivery_items', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_items_product_id'), 'delivery_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_delivery_items_warehouse_id'), 'delivery_items', ['warehouse_id'], unique=False)
    op.create_table('scheduled_deliveries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_deliveries_product_id'), 'scheduled_deliveries', ['product_id'], unique=False)
    op.create_index(op.f('ix_scheduled_deliveries_scheduled_at'), 'scheduled_deliveries', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_deliveries_warehouse_id'), 'scheduled_deliveries', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_deliveries_warehouse_id'), table_name='scheduled_deliveries')
    op.drop_index(op.f('ix_scheduled_deliveries_scheduled_at'), table_name='scheduled_deliveries')
    op.drop_index(op.f('ix_scheduled_deliveries_product_id'), table_name='scheduled_deliveries')
    op.drop_table('scheduled_deliveries')
    op.drop_index(op.f('ix_delivery_items_warehouse_id'), table_name='delivery_items')
    op.drop_index(op.f('ix_delivery_items_product_id'), table_name='delivery_items')
    op.drop_index(op.f('ix_delivery_items_delivery_id'), table_name='delivery_items')
    op.drop_table('delivery_items')
    op.drop_index(op.f('ix_deliveries_warehouse_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_scheduled_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_name'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivered_at'), table_name='deliveries')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
